# Global site config
site:
  name: Site Lightning
  url: http://sitelightning.co

# Main menu
header:
  - name: Documentation
    url: /documentation/
  - name: Tutorials
    url: /tutorials/

# Footer menu
footer:
  - name: Contact
    url: /contact/
  - name: Terms of Service
    url: /terms/
  - name: License
    url: /license/

# Social Menu
social:
  - github: http://github.com/abstracthat
  - twitter: @abstracthat
  # - facebook: 
  # - instagram: 
  # - pinterest: 
  # - youtube: 
