# Global site config
site:
  name: Site Lightning
  url: http://sitelightning.co

# Main menu
header:
  - name: Documentation
    url: /documentation/
  - name: Contact
    url: /contact/

# Footer menu
footer:
  - name: Terms of Service
    url: /terms/
  - name: License
    url: /license/

# Social Menu
social:
  - github: http://github.com/abstracthat
  - twitter: @abstracthat
  # - facebook: 
  # - instagram: 
  # - pinterest: 
  # - youtube: 

# Mailchimp
# Get your user ID from an existing list's form, it's the 'u' value.
# The submit url is the action url for the form.
# These are the same across all lists in your account. Here's how to find them:
# http://kb.mailchimp.com/lists/signup-forms/host-your-own-signup-forms
mailchimp:
  submit: http://marketfurther.us10.list-manage.com/subscribe/post
  user: aa52d5e1b14f1c50429ce9c39